"""add_merchant_onboarding_tables

Revision ID: 67994d65ccf6
Revises: dbb47d052c07
Create Date: 2026-09-24 14:01:29.832772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67994d65ccf6'
down_revision: Union[str, Sequence[str], None] = 'dbb47d052c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('social_instagram', sa.String(length=100), nullable=True),
    sa.Column('social_twitter', sa.String(length=100), nullable=True),
    sa.Column('social_facebook', sa.String(length=100), nullable=True),
    sa.Column('social_linkedin', sa.String(length=100), nullable=True),
    sa.Column('social_tiktok', sa.String(length=100), nullable=True),
    sa.Column('is_registered_business', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('registration_doc_path', sa.String(length=500), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), server_default='not_started', nullable=False),
    sa.Column('kyc_document_path', sa.String(length=500), nullable=True),
    sa.Column('kyc_document_type', sa.String(length=50), nullable=True),
    sa.Column('nin', sa.String(length=11), nullable=True),
    sa.Column('kyc_dojah_session_id', sa.String(length=200), nullable=True),
    sa.Column('kyc_reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('kyc_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('wallet_added', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('onboarding_step', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kyc_status IN ('not_started','pending','approved','rejected')", name='ck_merchant_profiles_kyc_status'),
    sa.ForeignKeyConstraint(['kyc_reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_merchant_profiles_user_id')
    )
    op.create_table('merchant_wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active','pending','inactive')", name='ck_merchant_wallets_status'),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Partial unique index: at most one active/pending wallet per merchant per network.
    # SQLAlchemy's UniqueConstraint does not support WHERE clauses, so this must be
    # created manually. The WHERE clause is a SQLite/PostgreSQL compatible predicate.
    op.execute(
        "CREATE UNIQUE INDEX uq_wallet_active ON merchant_wallets "
        "(merchant_id, network) WHERE status IN ('active','pending')"
    )

    op.create_table('payment_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('amount_mode', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=18), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('accepted_tokens', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('redirect_url', sa.String(length=2048), nullable=True),
    sa.Column('total_collected', sa.Numeric(precision=28, scale=18), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("amount_mode IN ('fixed','flexible')", name='ck_payment_links_amount_mode'),
    sa.CheckConstraint("status IN ('active','inactive','suspended_by_admin')", name='ck_payment_links_status'),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index('idx_payment_links_merchant', ['merchant_id'], unique=False)
        batch_op.create_index('idx_payment_links_slug', ['slug'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('payment_link_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=254), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('accepted_tokens', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','sent','viewed','paid','overdue','cancelled')", name='ck_invoices_status'),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoices_merchant', ['merchant_id'], unique=False)
        batch_op.create_index('idx_invoices_status', ['status'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_link_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('network', sa.String(length=64), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=True),
    sa.Column('from_address', sa.String(length=42), nullable=True),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','detected','confirming','confirmed','paid')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_link', ['payment_link_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('idx_payments_link')

    op.drop_table('payments')
    op.drop_table('invoice_line_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('idx_invoices_status')
        batch_op.drop_index('idx_invoices_merchant')

    op.drop_table('invoices')
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_links_slug')
        batch_op.drop_index('idx_payment_links_merchant')

    op.drop_table('payment_links')
    # Drop the partial unique index before dropping the table.
    op.execute("DROP INDEX IF EXISTS uq_wallet_active")
    op.drop_table('merchant_wallets')
    op.drop_table('merchant_profiles')
    # ### end Alembic commands ###
